#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=90
USE_PROCD=1

add_vlmcs_entry() {
	local new_hostname="$1"

	uci -q batch <<-EOF >/dev/null
		add dhcp srvhost
		set dhcp.@srvhost[-1].srv=_vlmcs._tcp
		set dhcp.@srvhost[-1].target=$new_hostname
		set dhcp.@srvhost[-1].port=1688
		set dhcp.@srvhost[-1].class=0
		set dhcp.@srvhost[-1].weight=100
		commit dhcp
	EOF

	/etc/init.d/dnsmasq restart
}

start_service() {
	config_load vlmcsd
	config_get_bool enabled config enabled 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/vlmcsd -D -i /etc/vlmcsd/vlmcsd.ini -L 0.0.0.0:1688 -L [::]:1688
	procd_set_param respawn 3600 5 5
	procd_close_instance

	config_get_bool autoactivate config autoactivate 1
	if [ "$autoactivate" -eq 1 ]; then
		local HOSTNAME
		HOSTNAME="$(uci -q get system.@system[0].hostname)"

		local index=$(uci -q show dhcp |grep "].srv='_vlmcs._tcp'") \
			|| add_vlmcs_entry $HOSTNAME
		index=${index#*[}
		index=${index%]*}

		local host_name=$(uci -q get dhcp.@srvhost[$index].target)

		if [ "$HOSTNAME" != "$host_name" ]; then
			uci delete dhcp.@srvhost[$index]
			add_vlmcs_entry $HOSTNAME
		fi
	fi
}

service_triggers() {
	procd_add_reload_trigger "vlmcsd"
}

reload_service() {
	stop
	start
}
